language: cpp
os: linux
dist: bionic
services:
  - docker
env:
  - IMAGE=ubuntu:latest DOCKERFILE=debian
  - IMAGE=ubuntu:rolling DOCKERFILE=debian
  - IMAGE=ubuntu:devel DOCKERFILE=debian
  - IMAGE=debian:stable DOCKERFILE=debian
  - IMAGE=debian:testing DOCKERFILE=debian
  - IMAGE=debian:unstable DOCKERFILE=debian
  - IMAGE=opensuse/leap:latest DOCKERFILE=opensuse
  - IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
# ppc64le support code  
  - IMAGE=ubuntu:latest DOCKERFILE=debian
    arch: ppc64le
  - IMAGE=ubuntu:rolling DOCKERFILE=debian
    arch: ppc64le
  - IMAGE=ubuntu:devel DOCKERFILE=debian
    arch: ppc64le
  - IMAGE=debian:stable DOCKERFILE=debian
    arch: ppc64le
  - IMAGE=debian:testing DOCKERFILE=debian
    arch: ppc64le
  - IMAGE=debian:unstable DOCKERFILE=debian
    arch: ppc64le
  - IMAGE=opensuse/leap:latest DOCKERFILE=opensuse
    arch: ppc64le
  - IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
    arch: ppc64le
jobs:
  allow_failures:
    - env: IMAGE=debian:stable DOCKERFILE=debian
    - env: IMAGE=debian:testing DOCKERFILE=debian
    - env: IMAGE=debian:unstable DOCKERFILE=debian
    - env: IMAGE=opensuse/leap:latest DOCKERFILE=opensuse
    - env: IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
#ppc64le support code
    - env: IMAGE=debian:stable DOCKERFILE=debian
      arch: ppc64le
    - env: IMAGE=debian:testing DOCKERFILE=debian
      arch: ppc64le
    - env: IMAGE=debian:unstable DOCKERFILE=debian
      arch: ppc64le
    - env: IMAGE=opensuse/leap:latest DOCKERFILE=opensuse
      arch: ppc64le
    - env: IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
      arch: ppc64le

before_install:
  - docker build --build-arg IMAGE=$IMAGE -t img -f test/dockerfiles/Dockerfile.$DOCKERFILE .
script:
  - docker run img
